'use client'
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { redirect, usePathname } from "next/navigation";
import { useContext, useEffect } from "react";
import { LoadingContextC, LoadingContext } from "./LoadingContext";
import { Modal } from "antd";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const path = usePathname();
  useEffect(()=>{
    const token = sessionStorage.getItem('token')
    if(!token && path != '/login') {redirect('/login')}
  },[path])

  return (
    <html lang="en">
      
      <body className={inter.className}>
        <LoadingContextC>
          {children}
        </LoadingContextC>
        </body>
    </html>
  );
}
